Sound feedback
WildCodeSchool/lille-0919-js-projet2-zeldaSnes pull request #10
Opened 2019-10-28 08:49 UTC by dderancourt

US 41, sound feedback when player can't make a move

2019-10-28 15:24 UTC, Gumatan submitted a review, later dismissed

2019-10-31 01:34 UTC, LoicBrassart submitted a review, later dismissed
SnE

2019-11-04 08:38 UTC, TheoBoschetti submitted a review, later dismissed
ok

2019-11-05 18:33 UTC, LoicBrassart requested changes
Evil spotted!

2019-11-05 18:33 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +      canMove: true,
Your file is broken (just checked after a `git pull` on my machine)

2019-11-06 09:39 UTC, merged