NPC can now attack, player loose HP
WildCodeSchool/lille-0919-js-projet2-zeldaSnes pull request #23
Opened 2019-11-07 16:18 UTC by dderancourt

2019-11-07 16:20 UTC, TheoBoschetti submitted a review, later dismissed
ok

2019-11-12 13:51 UTC, TheoBoschetti submitted a review, later dismissed
ok

2019-11-12 15:30 UTC, LoicBrassart requested changes
- `pahtfinder.js` ? :p 
- `var` ?!
- `console.log` is forbidden, I want an empty console!

2019-11-12 15:56 UTC, TheoBoschetti submitted a review, later dismissed
ok

2019-11-12 15:59 UTC, TheoBoschetti submitted a review, later dismissed
ok

2019-11-12 17:08 UTC, LoicBrassart requested changes

2019-11-12 17:08 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +  playBounce() {}
Nope!

2019-11-12 17:21 UTC, TheoBoschetti approved these changes
ok

2019-11-12 17:21 UTC, LoicBrassart approved these changes
SnE

2019-11-12 17:21 UTC, merged