About page final
WildCodeSchool/lille-0919-js-projet2-zeldaSnes pull request #29
Opened 2019-11-13 10:34 UTC by TheoBoschetti

2019-11-13 12:03 UTC, ghost submitted a review, later dismissed

2019-11-14 09:21 UTC, LoicBrassart requested changes
I'm sure @GautierMille didn't read through this.
We're on the last PRs on this project, but please keep up good practices

2019-11-14 09:21 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +    // this.getGamepad();
Nope

2019-11-14 09:21 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +    // }
Nope nope nope

2019-11-14 09:21 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +      if (path.length > 0 && path.length < 10) {
Nothing to do with the About page

2019-11-14 09:21 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +  // }
NOOOOOOOOOOOOOOOOOOOOO !!!!!!!!!!!!

2019-11-14 09:39 UTC, GautierMille commented
ok

2019-11-14 09:39 UTC, ghost approved these changes

2019-11-14 09:50 UTC, LoicBrassart approved these changes
SnE

2019-11-14 09:52 UTC, merged