Pnj feature
WildCodeSchool/lille-0919-js-projet2-zeldaSnes pull request #3
Opened 2019-10-24 19:03 UTC by dderancourt

PNJ feature added

2019-10-25 06:18 UTC, LoicBrassart requested changes
In English, it's called an NPC... Please change everything <3

2019-10-25 11:32 UTC, Gumatan submitted a review, later dismissed

2019-10-28 09:35 UTC, LoicBrassart requested changes
Some things to update

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +      xNPC: 10,
You could have created a nested object for this object's state instead of prefixing some fields with "PNJ"

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
>      let x = this.state.x;
Tip: this instruction would have worked too:: `let {x, y, xNPC, yNPC} = state`

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +        if (
Advice: This condition gets more and more complicated with every feature you add... You'll have to do something about it soon

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +  getAttack(event) {
- `getSomething()` shouldn't change anything
- (I think you should have added your enemy in an array, to be able to use several of them)
- Your case letters should be in English and uppercase
- What's keyCode 69 ? A bad joke ? Use the `key` property instead of the `keyCode`

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +  getNPCMove(indexNPCmove) {
- Shouldn't change anything
- Code copy-paste, that's not a good aidea, couldn't you have done anything better ?

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/Game.jsx
> +          {this.state.NPCIsAlive && (
It would have been better to have a PNJ component and separate your logic

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/NPC/NPC.css
> +.NPCdead {
I may be wrong, but I think this class is useless: if your NPC is dead, it's not included in the render at all

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/NPC/NPC.jsx
> +
Useless empty line

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/NPC/NPC.jsx
> +      case "g":
French direction names

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/NPC/NPC.jsx
> +          // display: this.props.NPCIsAlive ? "block" : "none",
Dead code

2019-10-28 09:35 UTC, LoicBrassart commented on frontend/src/Components/NPC/NPC.jsx
> +          top: `${this.props.yNPC * 32}px`,
Hard-coded value

2019-10-28 10:57 UTC, dderancourt commented on frontend/src/Components/Game.jsx
>      let x = this.state.x;
xNPC and yNPC are now nested object, what's the syntax when we want to use NPC.x ?

2019-10-28 15:45 UTC, Gumatan approved these changes

2019-10-31 00:32 UTC, LoicBrassart approved these changes
Good job on fixing this one

2019-11-04 08:31 UTC, merged